### ISSUE TITLE
Validation step for self referencing products

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtg-sealed-content#197]
```yaml
  Modern Horizons 3 Gift Bundle Case:
    sealed:
    - count: 6
      name: Modern Horizons 3 Gift Bundle Case
      set: mh3
```

this is problematic, would it be possible to add a validation step to avoid products referencing themselves?
