### ISSUE TITLE
consider use a string to indicate card finish for Sealed.Content.Card

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtg-sealed-content#33]
```yaml
    card:
    - set: one
      name: Phyrexian Arena
      number: 283
      foil: true
```

Instead of a boolean `foil` field there should be an option to select the finish property as reported by mtgjson/scryfall, that is a string for `nonfoil`, `foil` and `etched` - this would make it more consistent with the style used elsewhere, in particular in  `Decks`
